/*
 * petstore.net Inc.
 * Copyright (c) 2020 - 2023 All Rights Reserved.
 * Powered By [dalgen]
 */
 
package net.petstore.common.dal.dalgen.mybatis;

import net.petstore.common.dal.dalgen.operation.payment.*;
import net.petstore.common.dal.dalgen.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import net.petstore.common.dal.utils.PageQueryUtils;
import net.petstore.common.dal.utils.PageQuery;
import net.petstore.common.dal.utils.Paginator;
import net.petstore.common.dal.utils.PageList;



import org.mybatis.spring.support.SqlSessionDaoSupport;
import org.springframework.dao.DataAccessException;

import net.petstore.common.dal.dalgen.dataobject.PaymentDO;
import net.petstore.common.dal.dalgen.daointerface.PaymentDAO;

/**
 * PaymentDao
 * database table: payment
 * database table comments: Payment
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author dalgen
 *
 
 */
public class MybatisPaymentDAO extends SqlSessionDaoSupport implements PaymentDAO {


	/**
	 * 
	 * sql: 
	 * <pre>INSERT      INTO         payment         (           id ,uuid ,amt ,status ,gmt_created ,payment_time ,pay_channel           )      VALUES         (?,?,?,?,?,?,?)</pre>
	 */
	@Override
	public Integer insert(PaymentDO payment) throws DataAccessException {
		if(payment == null) {
			throw new IllegalArgumentException("Can't insert a null data object into db.");
		}
		getSqlSession().insert("petstore_Payment_insert", payment);
		return payment.getId();
	}

	/**
	 * 
	 * sql: 
	 * <pre>DELETE      FROM         payment      WHERE         id = ?</pre>
	 */
	@Override
	public int delete(Integer id) throws DataAccessException {
		return getSqlSession().delete("petstore_Payment_delete", id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>UPDATE         payment      SET         uuid = ? ,amt = ? ,status = ? ,gmt_created = ? ,payment_time = ? ,pay_channel = ?                WHERE         id = ?</pre>
	 */
	@Override
	public int update(PaymentDO payment) throws DataAccessException {
		if(payment == null) {
			throw new IllegalArgumentException("Can't update by a null data object.");
		}
		return getSqlSession().update("petstore_Payment_update", payment);
	}

	/**
	 * 
	 * sql: 
	 * <pre>UPDATE         payment          set         uuid = ? ,                amt = ? ,                status = ? ,                gmt_created = ? ,                payment_time = ? ,                pay_channel = ?                    where         id = ?</pre>
	 */
	@Override
	public int updateIf(PaymentDO payment) throws DataAccessException {
		if(payment == null) {
			throw new IllegalArgumentException("Can't update by a null data object.");
		}
		return getSqlSession().update("petstore_Payment_updateIf", payment);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, uuid, amt, status, gmt_created, payment_time, pay_channel                  FROM         payment               WHERE         id = ?</pre>
	 */
	@Override
	public PaymentDO queryById(Integer id) throws DataAccessException {
		return getSqlSession().selectOne("petstore_Payment_queryById",id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, uuid, amt, status, gmt_created, payment_time, pay_channel                  FROM         payment      where         uuid = ?</pre>
	 */
	@Override
	public PaymentDO queryByUuid(String uuid) throws DataAccessException {
		return getSqlSession().selectOne("petstore_Payment_queryByUuid",uuid);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, uuid, amt, status, gmt_created, payment_time, pay_channel            FROM         payment          WHERE         uuid = ?                         AND amt = ?                         AND status = ?                         AND gmt_created = ?                         AND payment_time = ?                         AND pay_channel = ?</pre>
	 */
	@Override
	public PageList<PaymentDO> findPage(FindPageQuery param) throws DataAccessException {
		return PageQueryUtils.pageQuery(getSqlSession(),"petstore_Payment_findPage",param);
	}

}

