/*
 * petstore.net Inc.
 * Copyright (c) 2020 - 2023 All Rights Reserved.
 * Powered By [dalgen]
 */
 
package net.petstore.common.dal.dalgen.mybatis;

import net.petstore.common.dal.dalgen.operation.member.*;
import net.petstore.common.dal.dalgen.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import net.petstore.common.dal.utils.PageQueryUtils;
import net.petstore.common.dal.utils.PageQuery;
import net.petstore.common.dal.utils.Paginator;
import net.petstore.common.dal.utils.PageList;



import org.mybatis.spring.support.SqlSessionDaoSupport;
import org.springframework.dao.DataAccessException;

import net.petstore.common.dal.dalgen.dataobject.MemberDO;
import net.petstore.common.dal.dalgen.daointerface.MemberDAO;

/**
 * MemberDao
 * database table: member
 * database table comments: Member
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author dalgen
 *
 
 */
public class MybatisMemberDAO extends SqlSessionDaoSupport implements MemberDAO {


	/**
	 * 
	 * sql: 
	 * <pre>INSERT      INTO         member         (           id ,uuid ,real_name ,password ,phone_number ,age ,qq_number ,signup_date ,wechat_uid ,nick_name           )      VALUES         (?,?,?,?,?,?,?,?,?,?)</pre>
	 */
	@Override
	public Integer insert(MemberDO member) throws DataAccessException {
		if(member == null) {
			throw new IllegalArgumentException("Can't insert a null data object into db.");
		}
		getSqlSession().insert("petstore_Member_insert", member);
		return member.getId();
	}

	/**
	 * 
	 * sql: 
	 * <pre>DELETE      FROM         member      WHERE         id = ?</pre>
	 */
	@Override
	public int delete(Integer id) throws DataAccessException {
		return getSqlSession().delete("petstore_Member_delete", id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>UPDATE         member      SET         uuid = ? ,real_name = ? ,password = ? ,phone_number = ? ,age = ? ,qq_number = ? ,signup_date = ? ,wechat_uid = ? ,nick_name = ?                WHERE         id = ?</pre>
	 */
	@Override
	public int update(MemberDO member) throws DataAccessException {
		if(member == null) {
			throw new IllegalArgumentException("Can't update by a null data object.");
		}
		return getSqlSession().update("petstore_Member_update", member);
	}

	/**
	 * 
	 * sql: 
	 * <pre>UPDATE         member          set         uuid = ? ,                real_name = ? ,                password = ? ,                phone_number = ? ,                age = ? ,                qq_number = ? ,                signup_date = ? ,                wechat_uid = ? ,                nick_name = ?                    where         id = ?</pre>
	 */
	@Override
	public int updateIf(MemberDO member) throws DataAccessException {
		if(member == null) {
			throw new IllegalArgumentException("Can't update by a null data object.");
		}
		return getSqlSession().update("petstore_Member_updateIf", member);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, uuid, real_name, password, phone_number, age, qq_number, signup_date, wechat_uid, nick_name                  FROM         member               WHERE         id = ?</pre>
	 */
	@Override
	public MemberDO queryById(Integer id) throws DataAccessException {
		return getSqlSession().selectOne("petstore_Member_queryById",id);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, uuid, real_name, password, phone_number, age, qq_number, signup_date, wechat_uid, nick_name                  FROM         member      where         uuid = ?</pre>
	 */
	@Override
	public MemberDO queryByUuid(String uuid) throws DataAccessException {
		return getSqlSession().selectOne("petstore_Member_queryByUuid",uuid);
	}

	/**
	 * 
	 * sql: 
	 * <pre>SELECT         id, uuid, real_name, password, phone_number, age, qq_number, signup_date, wechat_uid, nick_name            FROM         member          WHERE         uuid = ?                         AND real_name = ?                         AND password = ?                         AND phone_number = ?                         AND age = ?                         AND qq_number = ?                         AND signup_date = ?                         AND wechat_uid = ?                         AND nick_name = ?</pre>
	 */
	@Override
	public PageList<MemberDO> findPage(FindPageQuery param) throws DataAccessException {
		return PageQueryUtils.pageQuery(getSqlSession(),"petstore_Member_findPage",param);
	}

}

