
/*
 * petstore.net Inc.
 * Copyright (c) 2020 - 2023 All Rights Reserved.
 * Powered By [dalgen]
 */

package net.petstore.common.dal.dalgen.operation.member;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import net.petstore.common.dal.utils.PageQueryUtils;
import net.petstore.common.dal.utils.PageQuery;
import net.petstore.common.dal.utils.Paginator;
import net.petstore.common.dal.utils.PageList;



/**
 * database table: member
 * database table comments: Member
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author dalgen
 *
 
 */
public class FindPageQuery  extends PageQuery implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/** uuid */
	private String uuid;
	/** realName */
	private String realName;
	/** password */
	private String password;
	/** phoneNumber */
	private String phoneNumber;
	/** age */
	private String age;
	/** qqNumber */
	private String qqNumber;
	/** signupDate */
	private String signupDate;
	/** wechatUid */
	private String wechatUid;
	/** nickName */
	private String nickName;
	
	public FindPageQuery() {
	}
	
	public FindPageQuery(String uuid ,String realName ,String password ,String phoneNumber ,String age ,String qqNumber ,String signupDate ,String wechatUid ,String nickName ) {
		this.uuid = uuid;
		this.realName = realName;
		this.password = password;
		this.phoneNumber = phoneNumber;
		this.age = age;
		this.qqNumber = qqNumber;
		this.signupDate = signupDate;
		this.wechatUid = wechatUid;
		this.nickName = nickName;
	}
	
	public String getUuid() {
		return uuid;
	}
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	public String getRealName() {
		return realName;
	}
	public void setRealName(String realName) {
		this.realName = realName;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getPhoneNumber() {
		return phoneNumber;
	}
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	public String getAge() {
		return age;
	}
	public void setAge(String age) {
		this.age = age;
	}
	public String getQqNumber() {
		return qqNumber;
	}
	public void setQqNumber(String qqNumber) {
		this.qqNumber = qqNumber;
	}
	public String getSignupDate() {
		return signupDate;
	}
	public void setSignupDate(String signupDate) {
		this.signupDate = signupDate;
	}
	public String getWechatUid() {
		return wechatUid;
	}
	public void setWechatUid(String wechatUid) {
		this.wechatUid = wechatUid;
	}
	public String getNickName() {
		return nickName;
	}
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

    @Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}
