/*
 * petstore.net Inc.
 * Copyright (c) 2020 - 2023 All Rights Reserved.
 * Powered By [dalgen]
 */

package net.petstore.common.dal.dalgen.dataobject;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import net.petstore.common.dal.utils.PageQueryUtils;
import net.petstore.common.dal.utils.PageQuery;
import net.petstore.common.dal.utils.Paginator;
import net.petstore.common.dal.utils.PageList;



/**
 * MemberDO
 * database table: member
 * database table comments: Member
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author dalgen
 *
 
 */
public class MemberDO implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/**
	 * id 		db_column: id 
	 */
	private Integer id;
	/**
	 * uuid 		db_column: uuid 
	 */
	private String uuid;
	/**
	 * realName 		db_column: real_name 
	 */
	private String realName;
	/**
	 * password 		db_column: password 
	 */
	private String password;
	/**
	 * phoneNumber 		db_column: phone_number 
	 */
	private String phoneNumber;
	/**
	 * age 		db_column: age 
	 */
	private String age;
	/**
	 * qqNumber 		db_column: qq_number 
	 */
	private String qqNumber;
	/**
	 * signupDate 		db_column: signup_date 
	 */
	private String signupDate;
	/**
	 * wechatUid 		db_column: wechat_uid 
	 */
	private String wechatUid;
	/**
	 * nickName 		db_column: nick_name 
	 */
	private String nickName;

	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getId() {
		return this.id;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public String getUuid() {
		return this.uuid;
	}
	
	public void setRealName(String realName) {
		this.realName = realName;
	}
	
	public String getRealName() {
		return this.realName;
	}
	
	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getPassword() {
		return this.password;
	}
	
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	
	public String getPhoneNumber() {
		return this.phoneNumber;
	}
	
	public void setAge(String age) {
		this.age = age;
	}
	
	public String getAge() {
		return this.age;
	}
	
	public void setQqNumber(String qqNumber) {
		this.qqNumber = qqNumber;
	}
	
	public String getQqNumber() {
		return this.qqNumber;
	}
	
	public void setSignupDate(String signupDate) {
		this.signupDate = signupDate;
	}
	
	public String getSignupDate() {
		return this.signupDate;
	}
	
	public void setWechatUid(String wechatUid) {
		this.wechatUid = wechatUid;
	}
	
	public String getWechatUid() {
		return this.wechatUid;
	}
	
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}
	
	public String getNickName() {
		return this.nickName;
	}

	@Override
	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("Uuid",getUuid())
			.append("RealName",getRealName())
			.append("Password",getPassword())
			.append("PhoneNumber",getPhoneNumber())
			.append("Age",getAge())
			.append("QqNumber",getQqNumber())
			.append("SignupDate",getSignupDate())
			.append("WechatUid",getWechatUid())
			.append("NickName",getNickName())
			.toString();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}

	@Override
	public boolean equals(Object obj) {
		if(obj == null) {return false;}
		if(this == obj) {return true;}
		if(!(obj instanceof MemberDO)) {return false;}
		MemberDO other = (MemberDO)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
}

