/*
 * petstore.net Inc.
 * Copyright (c) 2020 - 2023 All Rights Reserved.
 * Powered By [dalgen]
 */

package net.petstore.common.dal.dalgen.dataobject;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import net.petstore.common.dal.utils.PageQueryUtils;
import net.petstore.common.dal.utils.PageQuery;
import net.petstore.common.dal.utils.Paginator;
import net.petstore.common.dal.utils.PageList;



/**
 * PaymentDO
 * database table: payment
 * database table comments: Payment
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author dalgen
 *
 
 */
public class PaymentDO implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/**
	 * id 		db_column: id 
	 */
	private Integer id;
	/**
	 * uuid 		db_column: uuid 
	 */
	private String uuid;
	/**
	 * 订单金额 		db_column: amt 
	 */
	private Double amt;
	/**
	 * status 		db_column: status 
	 */
	private String status;
	/**
	 * 订单创建时间 		db_column: gmt_created 
	 */
	private Date gmtCreated;
	/**
	 * 支付时间 		db_column: payment_time 
	 */
	private Date paymentTime;
	/**
	 * 支付渠道 		db_column: pay_channel 
	 */
	private String payChannel;

	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Integer getId() {
		return this.id;
	}
	
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	public String getUuid() {
		return this.uuid;
	}
	
	public void setAmt(Double amt) {
		this.amt = amt;
	}
	
	public Double getAmt() {
		return this.amt;
	}
	
	public void setStatus(String status) {
		this.status = status;
	}
	
	public String getStatus() {
		return this.status;
	}
	
	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}
	
	public Date getGmtCreated() {
		return this.gmtCreated;
	}
	
	public void setPaymentTime(Date paymentTime) {
		this.paymentTime = paymentTime;
	}
	
	public Date getPaymentTime() {
		return this.paymentTime;
	}
	
	public void setPayChannel(String payChannel) {
		this.payChannel = payChannel;
	}
	
	public String getPayChannel() {
		return this.payChannel;
	}

	@Override
	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("Uuid",getUuid())
			.append("Amt",getAmt())
			.append("Status",getStatus())
			.append("GmtCreated",getGmtCreated())
			.append("PaymentTime",getPaymentTime())
			.append("PayChannel",getPayChannel())
			.toString();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}

	@Override
	public boolean equals(Object obj) {
		if(obj == null) {return false;}
		if(this == obj) {return true;}
		if(!(obj instanceof PaymentDO)) {return false;}
		PaymentDO other = (PaymentDO)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
}

