
/*
 * petstore.net Inc.
 * Copyright (c) 2020 - 2023 All Rights Reserved.
 * Powered By [dalgen]
 */

package net.petstore.common.dal.dalgen.operation.payment;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import net.petstore.common.dal.utils.PageQueryUtils;
import net.petstore.common.dal.utils.PageQuery;
import net.petstore.common.dal.utils.Paginator;
import net.petstore.common.dal.utils.PageList;



/**
 * database table: payment
 * database table comments: Payment
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author dalgen
 *
 
 */
public class FindPageQuery  extends PageQuery implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/** uuid */
	private String uuid;
	/** 订单金额 */
	private Double amt;
	/** status */
	private String status;
	/** 订单创建时间 */
	private java.util.Date gmtCreated;
	/** 支付时间 */
	private java.util.Date paymentTime;
	/** 支付渠道 */
	private String payChannel;
	
	public FindPageQuery() {
	}
	
	public FindPageQuery(String uuid ,Double amt ,String status ,java.util.Date gmtCreated ,java.util.Date paymentTime ,String payChannel ) {
		this.uuid = uuid;
		this.amt = amt;
		this.status = status;
		this.gmtCreated = gmtCreated;
		this.paymentTime = paymentTime;
		this.payChannel = payChannel;
	}
	
	public String getUuid() {
		return uuid;
	}
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	public Double getAmt() {
		return amt;
	}
	public void setAmt(Double amt) {
		this.amt = amt;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public java.util.Date getGmtCreated() {
		return gmtCreated;
	}
	public void setGmtCreated(java.util.Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}
	public java.util.Date getPaymentTime() {
		return paymentTime;
	}
	public void setPaymentTime(java.util.Date paymentTime) {
		this.paymentTime = paymentTime;
	}
	public String getPayChannel() {
		return payChannel;
	}
	public void setPayChannel(String payChannel) {
		this.payChannel = payChannel;
	}

    @Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}
