/*
 * petstore.net Inc.
 * Copyright (c) 2020 - 2023 All Rights Reserved.
 * Powered By [dalgen]
 */
package net.petstore.common.dal.dalgen.daointerface;
import org.springframework.dao.DataAccessException;
import net.petstore.common.dal.dalgen.operation.payment.*;
import net.petstore.common.dal.dalgen.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import net.petstore.common.dal.utils.PageQueryUtils;
import net.petstore.common.dal.utils.PageQuery;
import net.petstore.common.dal.utils.Paginator;
import net.petstore.common.dal.utils.PageList;



/**
 * PaymentDAO
 * database table: payment
 * database table comments: Payment
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author dalgen
 *
 
 */
public interface PaymentDAO {


	/**
	 * 
	 * sql:
	 * <pre>INSERT      INTO         payment         (           id ,uuid ,amt ,status ,gmt_created ,payment_time ,pay_channel           )      VALUES         (?,?,?,?,?,?,?)</pre> 
	 */
	Integer insert(PaymentDO payment) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>DELETE      FROM         payment      WHERE         id = ?</pre> 
	 */
	int delete(Integer id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>UPDATE         payment      SET         uuid = ? ,amt = ? ,status = ? ,gmt_created = ? ,payment_time = ? ,pay_channel = ?                WHERE         id = ?</pre> 
	 */
	int update(PaymentDO payment) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>UPDATE         payment          set         uuid = ? ,                amt = ? ,                status = ? ,                gmt_created = ? ,                payment_time = ? ,                pay_channel = ?                    where         id = ?</pre> 
	 */
	int updateIf(PaymentDO payment) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, uuid, amt, status, gmt_created, payment_time, pay_channel                  FROM         payment               WHERE         id = ?</pre> 
	 */
	PaymentDO queryById(Integer id) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, uuid, amt, status, gmt_created, payment_time, pay_channel                  FROM         payment      where         uuid = ?</pre> 
	 */
	PaymentDO queryByUuid(String uuid) throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, uuid, amt, status, gmt_created, payment_time, pay_channel            FROM         payment          WHERE         uuid = ?                         AND amt = ?                         AND status = ?                         AND gmt_created = ?                         AND payment_time = ?                         AND pay_channel = ?</pre> 
	 */
	PageList<PaymentDO> findPage(FindPageQuery param) throws DataAccessException;

}



